name: learnify
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons/Media
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  flutter_svg: ^2.0.7
  
  # State management
  get: ^4.6.6
  provider: ^6.0.5
  
  # Routing
  go_router: 8.0.3
  
  # UI/UX
  percent_indicator: ^4.2.3
  flutter_staggered_grid_view: 0.4.1
  
  # Video kit
  video_player: ^2.7.2
  
  intl: ^0.18.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.2

  # Firebase service
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.0
  image_picker: 1.0.0
  email_validator: ^2.1.17
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/raster/.
    - assets/images/vector/.
    - assets/icons/.
    - assets/changeme/.

  fonts: 
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
